### ISSUE TITLE
Borked sort order

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#7]
On https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Women_in_Red/Metrics/Wikidata_humans_no_gender

Asks for sort=label

Gets sort=QId

**Comment by magnusmanske** [comment]
Fixed now ([example](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Women_in_Red/Metrics/Wikidata_humans_no_gender&oldid=989022079)).

**Comment by camelCaseNick** [comment]
@magnusmanske https://www.wikidata.org/wiki/User:CamelCaseNick/Stolpersteine/Hamburg has this issue as well and it seems to still persist or is the fix not yet fully rolled out? In contrast to the example above, in this list, the language is explicitly set via the `language` parameter.
